# Generated by Django 5.2.4 on 2025-08-27 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
