# Generated by Django 5.2.4 on 2025-08-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0002_alter_fee_unique_together_fee_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='username',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
