# Generated by Django 5.2.5 on 2025-08-28 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0004_student_profile_picture_teacher_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bri.attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bri.student')),
            ],
            options={
                'unique_together': {('student', 'attendance')},
            },
        ),
    ]
