# Generated by Django 5.2.5 on 2025-08-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0009_alter_class_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
