# Generated by Django 5.2.5 on 2025-08-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0010_teacher_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='bri.username'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='bri.username'),
        ),
    ]
