# Generated by Django 5.2.5 on 2025-08-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0012_test_test_name_alter_testsession_session_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeupdatelog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studenttestresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testsession',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='message_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studenttestresult',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='time_marked',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='session_type',
            field=models.CharField(choices=[('monthly', 'Monthly Test'), ('session_exam', 'Session Exam')], max_length=20),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='StudentExamResult',
        ),
    ]
