# Generated by Django 5.2.5 on 2025-08-30 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0013_alter_feeupdatelog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marksheet',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='marksheet',
            name='student',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Marksheet',
        ),
    ]
