# Generated by Django 5.2.5 on 2025-09-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0016_student_bform'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
