# Generated by Django 5.2.5 on 2025-09-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0019_student_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
