# Generated by Django 5.2.4 on 2025-08-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0003_username_full_name_username_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_pics/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_pics/'),
        ),
    ]
