# Generated by Django 5.2.5 on 2025-08-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0005_attendancenotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('fee_reminder', 'Fee Reminder'), ('attendance', 'Attendance Notification'), ('general', 'General Message'), ('exam', 'Exam Notification')], max_length=20)),
                ('message_text', models.TextField(help_text='Use {STUDENT_NAME}, {AMOUNT}, {MONTH}, {CLASS}, {SECTION} as placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Fee Created'), ('submitted', 'Fee Submitted to Students'), ('payment', 'Fee Payment Recorded'), ('updated', 'Fee Updated'), ('deleted', 'Fee Deleted')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bri.fee')),
                ('student_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bri.studentfee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bri.username')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=7)),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bri.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bri.section')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('test_type', models.CharField(choices=[('written', 'Written Test'), ('oral', 'Oral Test'), ('practical', 'Practical Test'), ('assignment', 'Assignment')], default='written', max_length=20)),
                ('total_marks', models.IntegerField()),
                ('test_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='bri.testsession')),
            ],
            options={
                'ordering': ['test_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.FloatField()),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bri.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bri.test')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'test')},
            },
        ),
    ]
