# Generated by Django 5.2.5 on 2025-08-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0006_messagetemplate_feeupdatelog_testsession_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='session_type',
            field=models.CharField(choices=[('monthly', 'Monthly Test'), ('session_exam', 'Test Session Exam')], default='monthly', max_length=20),
        ),
    ]
