# Generated by Django 5.2.5 on 2025-08-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0008_remove_test_test_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['order', 'class_name']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'std_section']},
        ),
        migrations.AddField(
            model_name='class',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
