# Generated by Django 5.2.5 on 2025-08-29 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0011_alter_student_username_alter_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='e.g., Test 1, Test 2, Mid Term, Final', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsession',
            name='session_type',
            field=models.CharField(choices=[('monthly', 'Monthly Test'), ('session_exam', 'Session Exam')], default='monthly', max_length=20),
        ),
    ]
