# Generated by Django 5.2.5 on 2025-09-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0015_useractivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bform',
            field=models.CharField(blank=True, help_text='B-Form number', max_length=20, null=True),
        ),
    ]
