# Generated by Django 5.2.5 on 2025-09-08 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0017_student_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappmessage',
            old_name='sent_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bform',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='student',
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='sent', max_length=10),
        ),
    ]
