# Generated by Django 5.2.5 on 2025-09-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bri', '0020_student_bform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_roll',
            field=models.CharField(max_length=20),
        ),
    ]
